services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - '8080:8080'
    volumes:
      - pb_data:/pb/pb_data
volumes:
  pb_data:
    driver: local
